sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.33.0
os:
  - linux
  - osx
#  - windows
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo

script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then cargo test headless; cargo test --doc; cargo test --test skeptic; fi
#  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cargo test --verbose headless --no-default-features; fi

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo apt-get -qq update
      && sudo apt-get install -y libasound2-dev libudev-dev;
    fi

after_success: |
  if [[ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_RUST_VERSION}" == stable ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    # Uncomment the following line for coveralls.io
    # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
