sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.33.0
os:
  - linux
  - osx
  - windows
matrix:
  allow_failures:
    - rust: nightly
cache: cargo

script:
  - cargo test;
  - cargo test --doc;
  - cargo test --test skeptic;

after_success: |
  if [[ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_RUST_VERSION}" == stable ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    # Uncomment the following line for coveralls.io
    # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
